openapi: "3.0.0"
info:
  version: 1.0.0
  title: Albi Backend
  description: Albicchiere backend docs
  license:
    name: MIT
  contact:
    name: API Support
    email: support@albicchiere.com
servers:
  - url: https://api-staging.albicchiere.com
  - url: https://api-dev.albicchiere.com
  - url: https://api-beta.albicchiere.com
paths:
  # #########################################################
  # companies
  # #########################################################
  /companies:
    $ref: "./paths/companies/companies.yaml"
  /companies/verify_admin_token:
    $ref: "./paths/companies/companyVerifyAdminToken.yaml"
  /companies/{companyId}:
    $ref: "./paths/companies/company.yaml"
  /companies/{companyId}/change_status:
    $ref: "./paths/companies/companyChangeStatus.yaml"
  /companies/{companyId}/overview:
    $ref: "./paths/companies/companyOverview.yaml"
  /companies/{companyId}/send_approval_request:
    $ref: "./paths/companies/companySendApprovalRequest.yaml"
  /companies/{companyId}/image:
    $ref: "./paths/companies/companyImage.yaml"
  # addresses
  /companies/{companyId}/addresses:
    $ref: "./paths/companies/companyAddresses.yaml"
  /companies/{companyId}/addresses/{addressId}:
    $ref: "./paths/companies/companyAddress.yaml"
  # user access
  /companies/{companyId}/user_accesses:
    $ref: "./paths/companies/companyUserAccesses.yaml"
  /companies/{companyId}/user_accesses/{accessId}:
    $ref: "./paths/companies/companyUserAccess.yaml"
  # company setting
  /companies/${companyId}/company_setting:
    $ref: "./paths/companies/companySetting.yaml"
  /companies/${companyId}/company_setting/${field}:
    $ref: "./paths/companies/companySettingField.yaml"
  /companies/${companyId}/company_setting/${field}/${name}:
    $ref: "./paths/companies/companySettingField.yaml"
  /companies/${companyId}/company_setting/${field}/${name}/image:
    $ref: "./paths/companies/companySettingFieldImage.yaml"
  # #########################################################
  # users
  # #########################################################
  /users:
    $ref: "./paths/users/users.yaml"
  /users/me:
    $ref: "./paths/users/userMe.yaml"
  /users/me/session:
    $ref: "./paths/users/userMeSession.yaml"
  /users/me/stats:
    $ref: "./paths/users/userMeStats.yaml"
  /users/me/locations:
    $ref: "./paths/users/userMeCompanyAccesses.yaml"
  /users/me/image:
    $ref: "./paths/users/userMeImage.yaml"
  /users/me/add_parental_control_on_vintage:
    $ref: "./paths/users/userMeAddParental.yaml"
  /users/me/remove_parental_control_on_vintage/{vintageId}:
    $ref: "./paths/users/userMeRemoveParental.yaml"
  /users/{userId}:
    $ref: "./paths/users/user.yaml"
  /users/me/wishlist:
    $ref: "./paths/users/userWishlist.yaml"
  /users/me/wishlist/add_vintage:
    $ref: "./paths/users/userWishlistAddVintage.yaml"
  /users/me/wishlist/remove_vintage/{vintageId}:
    $ref: "./paths/users/userWishlistRemoveVintage.yaml"
  /users/me/wishlist/share:
    $ref: "./paths/users/userWishlistShare.yaml"
  /users/me/wishlist/{sharedWishlistId}:
    $ref: "./paths/users/userGetWishlistShare.yaml"
  /users/me/reviews:
    $ref: "./paths/users/userReviews.yaml"
  # #########################################################
  # notifications
  # #########################################################
  /notifications/register_new_device:
    $ref: "./paths/notifications/registerNewDevice.yaml"
  /notifications/delete_device:
    $ref: "./paths/notifications/deleteDevice.yaml"
  /notifications:
    $ref: "./paths/notifications/notifications.yaml"
  # #########################################################
  # wine container
  # #########################################################
  /wine/wine_container_models:
    $ref: "./paths/wineContainers/wineContainers.yaml"
  /wine/wine_container_models/{id}:
    $ref: "./paths/wineContainers/wineContainer.yaml"
  # #########################################################
  # user vintages
  # #########################################################
  /wine/user_vintages:
    $ref: "./paths/userVintages/userVintages.yaml"
  /wine/user_vintages/{userVintageId}:
    $ref: "./paths/userVintages/userVintage.yaml"
  /wine/user_vintages/{userVintageId}/label:
    $ref: "./paths/userVintages/userVintageLabel.yaml"
  # #########################################################
  # wines
  # #########################################################
  /wine/wines:
    $ref: "./paths/wines/wines.yaml"
  /wine/wines/{wineId}:
    $ref: "./paths/wines/wine.yaml"
  /wine/wines/{wineId}/vintages:
    $ref: "./paths/wines/wineVintages.yaml"
  /wine/wines/vintages/{vintageId}:
    $ref: "./paths/wines/wineNoWineVintage.yaml"
  /wine/wines/{wineId}/vintages/{vintageId}:
    $ref: "./paths/wines/wineVintage.yaml"
  /wine/wines/{wineId}/vintages/{vintageId}/label:
    $ref: "./paths/wines/wineVintageLabel.yaml"
  /wine/wines/{wineId}/vintages/{vintageId}/image/{fileName}:
    $ref: "./paths/wines/wineVintageImage.yaml"
  /wine/wines/{wineId}/vintages/{vintageId}/reviews:
    $ref: "./paths/wines/wineVintageReviews.yaml"
  /wine/wines/{wineId}/vintages/{vintageId}/reviews/recap:
    $ref: "./paths/wines/wineVintageReviewsRecap.yaml"
  /wine/wines/{wineId}/vintages/{vintageId}/review:
    $ref: "./paths/wines/wineVintageReview.yaml"
  /wine/wines/scan_label:
    $ref: "./paths/wines/wineScanLabel.yaml"
  /wine/wines/random:
    $ref: "./paths/wines/wineRandomWines.yaml"
  /wine/wines/search:
    $ref: "./paths/wines/wineSearch.yaml"
  # #########################################################
  # cantina
  # #########################################################
  /cantina/cantina_vintages:
    $ref: "./paths/cantina/cantinaVintages.yaml"
  /cantina/smart_bags:
    $ref: "./paths/cantina/smartBags.yaml"
  /cantina/smart_bags/{smartBagId}:
    $ref: "./paths/cantina/smartBag.yaml"
  /cantina/smart_bags/{serial}/check_nfc:
    $ref: "./paths/cantina/smartBagCheckNFC.yaml"
  /cantina/smart_bags/{serial}/transfer_ownership:
    $ref: "./paths/cantina/smartBagOwnership.yaml"
  /cantina/smart_bags/{serial}/fill_smart_bag:
    $ref: "./paths/cantina/smartBagFill.yaml"
  /cantina/smart_bags/{serial}/refill_smart_bag:
    $ref: "./paths/cantina/smartBagRefill.yaml"
  /cantina/smart_bags/{serial}/set_custom_temperature:
    $ref: "./paths/cantina/smartBagCustopmTemp.yaml"
  /cantina/bottles:
    $ref: "./paths/cantina/bottles.yaml"
  /cantina/bottles/{bottleId}:
    $ref: "./paths/cantina/bottle.yaml"
  /cantina/bottles/{bottleId}/turn_into_bag:
    $ref: "./paths/cantina/bottleTurnIntoABag.yaml"
  /cantina/bottles/counters:
    $ref: "./paths/cantina/bottlesCounter.yaml"
  /cantina/bottles/{bottleId}/counters:
    $ref: "./paths/cantina/bottleCounter.yaml"
  # #########################################################
  # dispensers
  # #########################################################
  /dispenser/dispensers:
    $ref: "./paths/dispensers/dispensers.yaml"
  /dispenser/dispensers/{dispenserId}:
    $ref: "./paths/dispensers/dispenser.yaml"
  /dispenser/dispensers/{serial}/activate:
    $ref: "./paths/dispensers/dispenserActivation.yaml"
  /dispenser/dispensers/{dispenserId}/pour_wine:
    $ref: "./paths/dispensers/dispenserPourWine.yaml"
  /dispenser/dispensers/{dispenserId}/set_cooling_mode:
    $ref: "./paths/dispensers/dispenserSetCoolingMode.yaml"
  /dispenser/dispensers/{dispenserId}/set_schedule:
    $ref: "./paths/dispensers/dispenserSetSchedule.yaml"
  /dispenser/dispensers/{dispenserId}/remove_schedule:
    $ref: "./paths/dispensers/dispenserRemoveSchedule.yaml"
  /dispenser/dispensers/{dispenserId}/start_vacuum_bag:
    $ref: "./paths/dispensers/dispenserStartVacuumBag.yaml"
  # /dispenser/dispensers/{dispenserId}/set_serving_temperature:
  #   $ref: "./paths/dispensers/dispenserSetServingTemperature.yaml"
  /dispenser/dispensers/{dispenserId}/toggle_parental_control:
    $ref: "./paths/dispensers/dispenserToggleParentalControl.yaml"
  /dispenser/dispensers/{dispenserId}/get_data:
    $ref: "./paths/dispensers/dispenserData.yaml"
  # #########################################################
  # chassis
  # #########################################################
  /dispenser/chassis:
    $ref: "./paths/chassis/chassisBase.yaml"
  /dispenser/chassis/{chassisId}:
    $ref: "./paths/chassis/chassis.yaml"
  # #########################################################
  # dispenser rooms
  # #########################################################
  /dispenser/rooms:
    $ref: "./paths/dispenserRooms/rooms.yaml"
  /dispenser/rooms/{roomId}:
    $ref: "./paths/dispenserRooms/room.yaml"
  # #########################################################
  # jobs
  # #########################################################
  /dispenser/jobs:
    $ref: "./paths/dispenserJobs/jobs.yaml"
  /dispenser/jobs/{jobId}:
    $ref: "./paths/dispenserJobs/job.yaml"
  /dispenser/jobs/executed:
    $ref: "./paths/dispenserJobs/executedJobs.yaml"
  /dispenser/jobs/executed/{jobId}:
    $ref: "./paths/dispenserJobs/executedJob.yaml"
  # #########################################################
  # app_settings
  # #########################################################
  /app_settings/mobile_app_config/albi_sommelier:
    $ref: "./paths/mobileAppConfig/albiSommelier.yaml"
  /app_settings/mobile_app_config/home:
    $ref: "./paths/mobileAppConfig/home.yaml"
  /app_settings/mobile_app_config/search:
    $ref: "./paths/mobileAppConfig/search.yaml"
  # #########################################################
  # wine_setting
  # #########################################################
  /app_settings/wine_setting:
    $ref: "./paths/wineSetting/wineSetting.yaml"
  /app_settings/wine_setting/countries:
    $ref: "./paths/wineSetting/wineCountries.yaml"
  # #########################################################
  # elabel_setting
  # #########################################################
  /app_settings/elabel_setting:
    $ref: "./paths/elabelSetting/elabelSetting.yaml"
  # #########################################################
  # elabels
  # #########################################################
  /elabels:
    $ref: "./paths/elabels/elabels.yaml"
  /elabels/{elabelId}:
    $ref: "./paths/elabels/elabel.yaml"
  /elabels/{elabelId}/batches:
    $ref: "./paths/elabels/batches.yaml"
  /elabels/batches/{batchId}:
    $ref: "./paths/elabels/batch.yaml"
  # #########################################################
  # winelists
  # #########################################################
  /winelists:
    $ref: "./paths/winelists/winelists.yaml"
  /winelists/{wineListId}:
    $ref: "./paths/winelists/winelist.yaml"
  /winelists/disable_all:
    $ref: "./paths/winelists/disableAll.yaml"
  # #########################################################
  # production_tags
  # #########################################################
  /production_tags:
    $ref: "./paths/productionTags/productionTags.yaml"
  /production_tags/upload:
    $ref: "./paths/productionTags/productionTagsUpload.yaml"
  /production_tags/download-csv:
    $ref: "./paths/productionTags/downloadCSV.yaml"
  /production_tags/report_activated:
    $ref: "./paths/productionTags/reportActivated.yaml"
  /production_tags/report_canceled:
    $ref: "./paths/productionTags/reportCanceled.yaml"
  # #########################################################
  # roles
  # #########################################################
  /roles:
    $ref: "./paths/roles/roles.yaml"
  /roles/{roleId}:
    $ref: "./paths/roles/role.yaml"
  /roles/blocks:
    $ref: "./paths/roles/roleBlocks.yaml"
  /roles/blocks/{blockId}:
    $ref: "./paths/roles/roleBlock.yaml"
components:
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # #########################################################
    User:
      $ref: "./models/user.yaml"
    UserCompanyAccess:
      $ref: "./models/userCompanyAccess.yaml"
    UserStat:
      $ref: "./models/userStat.yaml"
    UserWishList:
      $ref: "./models/userWishlist.yaml"
    UserWishListShared:
      $ref: "./models/userWishlistShared.yaml"
    # #########################################################
    Company:
      $ref: "./models/company.yaml"
    Address:
      $ref: "./models/companyAddress.yaml"
    # #########################################################
    WineContainer:
      $ref: "./models/wineContainer.yaml"
    # #########################################################
    UserVintage:
      $ref: "./models/userVintage.yaml"
    # #########################################################
    Wine:
      $ref: "./models/wine.yaml"
    WineVintage:
      $ref: "./models/wineVintage.yaml"
    WineVintageReview:
      $ref: "./models/wineVintageReview.yaml"
    WineVintageReviewRecap:
      $ref: "./models/wineVintageReviewRecap.yaml"
    # #########################################################
    Bottle:
      $ref: "./models/bottle.yaml"
    SmartBag:
      $ref: "./models/smartBag.yaml"
    # #########################################################
    RoleBlock:
      $ref: "./models/roleBlock.yaml"
    Role:
      $ref: "./models/role.yaml"
    # #########################################################
    Dispenser:
      $ref: "./models/dispenser.yaml"
    Chassis:
      $ref: "./models/chassis.yaml"
    DispenserRoom:
      $ref: "./models/dispenserLocationRoom.yaml"
    Job:
      $ref: "./models/dispenserJob.yaml"
    ExecutedJob:
      $ref: "./models/dispenserExeJob.yaml"
    # #########################################################
